export interface Memory {
  id: number;
  type: 'postcard' | 'photo' | 'video';
  subject: string;
  place: string;
  month: string;
  subtitle: string;
  comment: string;
}

export const memoriesData: Memory[] = [
  {
    id: 1,
    type: 'postcard',
    subject: 't-rex-bones',
    place: 'MET',
    month: 'May',
    subtitle: 'Day trip',
    comment: 'I saw a T-Rex Bones for the first time!',
  },
  {
    id: 2,
    type: 'postcard',
    subject: 'grand-central-terminal',
    place: 'Grand Central Terminal',
    month: 'Jun',
    subtitle: 'Day trip',
    comment:
      'I keep seeing references to Madagascar, but what an impressive place!',
  },
  {
    id: 3,
    type: 'postcard',
    subject: 'booble-tea',
    place: 'San Francisco',
    month: 'March',
    subtitle: 'Park Day',
    comment: 'The bests bubble tea in SF!',
  },
  {
    id: 4,
    type: 'postcard',
    subject: 'cable-car',
    place: 'San Francisco',
    month: 'March',
    subtitle: 'First Day!',
    comment: 'I rode the cable car for the first time!',
  },
  {
    id: 5,
    type: 'postcard',
    subject: 'gioconda',
    place: 'Louvre Museum',
    month: 'Dec',
    subtitle: 'Museum Day!',
    comment: 'Well, I did see it — from about 10 meters away 😅',
  },
  {
    id: 6,
    type: 'postcard',
    subject: 'oculus',
    place: 'Oculus',
    month: 'Jun',
    subtitle: 'Day trip',
    comment: 'I went to the Oculus for the first time!',
  },
  {
    id: 7,
    type: 'postcard',
    subject: 'starry-night',
    place: 'MoMa',
    month: 'Jun',
    subtitle: 'Museum Day!',
    comment: 'I went to the MoMa for the first time!',
  },
  {
    id: 8,
    type: 'video',
    subject: 'ny-subway',
    place: 'NYC',
    month: 'Jun',
    subtitle: 'Day trip',
    comment: '',
  },
  {
    id: 9,
    type: 'postcard',
    subject: 'balto-statue',
    place: 'Central Park',
    month: 'Jun',
    subtitle: 'Park Day',
    comment:
      'This statue reminds me of the good times watching Balto when I was a kid.',
  },
  {
    id: 10,
    type: 'postcard',
    subject: 'eiffel-tower',
    place: 'Paris',
    month: 'Dec',
    subtitle: 'Amazing view!',
    comment: 'I love this monument! Is beautiful!',
  },
  {
    id: 11,
    type: 'postcard',
    subject: 'empire-state',
    place: 'NYC',
    month: 'Jun',
    subtitle: 'Dream Day!',
    comment:
      'The Empire State is so iconic, and it was honestly one of my favorite places when visiting NYC.',
  },
  {
    id: 12,
    type: 'postcard',
    subject: 'grand-cayon',
    place: 'California State',
    month: 'March',
    subtitle: 'Sunny Day!',
    comment: 'I love this place!',
  },
  {
    id: 13,
    type: 'postcard',
    subject: 'grand-palais',
    place: 'París, France',
    month: 'Dec',
    subtitle: 'Calm night walk',
    comment: 'One of the most beautiful places in the world!',
  },
  {
    id: 14,
    type: 'postcard',
    subject: 'hollywood-sign',
    place: 'Los Angeles',
    month: 'March',
    subtitle: 'Sunny Day!',
    comment: 'I love this place!',
  },
  {
    id: 15,
    type: 'postcard',
    subject: 'Louvre Museum',
    place: 'París. France',
    month: 'Dec',
    subtitle: 'Museum Day!',
    comment:
      'The size of the Louvre is truly surprising — absolutely impressive.',
  },
  {
    id: 16,
    type: 'postcard',
    subject: 'japan-garden',
    place: 'Japan Garden',
    month: 'Dec',
    subtitle: 'Beautiful day!',
    comment: 'I love this place!',
  },
  {
    id: 17,
    type: 'postcard',
    subject: 'notre-dame',
    place: 'íle de la Cité',
    month: 'Dec',
    subtitle: 'First day in París!',
    comment: 'A beautiful monument!',
  },
  {
    id: 18,
    type: 'postcard',
    subject: 'ballon-dog',
    place: 'The Broad Museum',
    month: 'March',
    subtitle: 'Downtown Day!',
    comment: '',
  },
  {
    id: 19,
    type: 'postcard',
    subject: 'one-world-trade',
    place: 'NYC',
    month: 'Dec',
    subtitle: 'Amazing view!',
    comment:
      'Im still amazed by how hard it is to grasp the size of One World — and the view is absolutely stunning!',
  },
  {
    id: 20,
    type: 'postcard',
    subject: 'palace-of-fine-arts',
    place: 'SF',
    month: 'March',
    subtitle: 'Beautiful monument!',
    comment:
      'I didn’t know about this place until I arrived in San Francisco — a must-see if you’re visiting the city!',
  },
  {
    id: 21,
    type: 'postcard',
    subject: 'best-bread',
    place: 'Any place in France',
    month: 'Dec',
    subtitle: 'The best bread I ever had!',
    comment:
      'I could undeniably eat boulangerie every single day if I lived in France.',
  },
  {
    id: 22,
    type: 'postcard',
    subject: 'arc-de-triomphe',
    place: 'Arc de Triomphe',
    month: 'Dec',
    subtitle: 'Amazing view!',
    comment: 'I love this place!',
  },
  {
    id: 23,
    type: 'postcard',
    subject: 'arrive-vegas',
    place: 'Vegas Airport',
    month: 'March',
    subtitle: 'Really?',
    comment:
      'Literally the first thing I saw when I arrived at the Las Vegas airport was slot machines xD',
  },
  {
    id: 24,
    type: 'postcard',
    subject: 'clamp-shoulder',
    place: 'Monterey Wharf',
    month: 'March',
    subtitle: 'Clamp shoulder!',
    comment: 'The best clamp shoulder I ever had!',
  },
  {
    id: 25,
    type: 'postcard',
    subject: 'universal-hollywood',
    place: 'Universal Studios Hollywood',
    month: 'March',
    subtitle: 'The best theme park I ever been!',
    comment:
      'It was a rainy day, but it let us explore and enjoy the park with no lines at all — probably a little hack! :D',
  },
  {
    id: 26,
    type: 'postcard',
    subject: 'vegas-sign',
    place: 'Las Vegas',
    month: 'March',
    subtitle: 'Slot machines to the max!',
    comment: 'I love this place!',
  },
  {
    id: 27,
    type: 'postcard',
    subject: 'waymo-car',
    place: 'San Francisco',
    month: 'March',
    subtitle: 'The best way to travel!',
    comment: 'Please let it come to LATAM!',
  },
  {
    id: 28,
    type: 'postcard',
    subject: 'waymo-car',
    place: 'San Francisco',
    month: 'March',
    subtitle: 'The best way to travel!',
    comment: 'Please let it come to LATAM!',
  },
  {
    id: 29,
    type: 'postcard',
    subject: 'waymo-car',
    place: 'San Francisco',
    month: 'March',
    subtitle: 'The best way to travel!',
    comment: 'Please let it come to LATAM!',
  },
  {
    id: 30,
    type: 'postcard',
    subject: 'yosemite-valley',
    place: 'Yosemite Day!',
    month: 'March',
    subtitle: 'A beautiful place in the world!',
    comment: 'One of the most wonderful experiences you can have.',
  },
];
