'use client';

import html2canvas from 'html2canvas';
import { useRef } from 'react';

/* 
This is a wallpaper maker page. I have problem creating the wallpaper, any scale in the DOM affect directly the quality of the image generated by html2Canvas.

The mainly purpose y create and image of 21:9 aspect ratio.

Por ahora la solucion es un scale en el export y el preview algo normal.
*/


const DownloadWallpaperPage = () => {
  const wallpaperRef = useRef<HTMLDivElement>(null);

  const handleDownload = async () => {
    if (!wallpaperRef.current) return;

    try {
      const wallpaperElement = wallpaperRef.current as HTMLDivElement;
      const canvas = await html2canvas(wallpaperElement, {
        scale: 3,
        backgroundColor: null,
        logging: false,
        removeContainer: true,
      });

      const image = canvas.toDataURL('image/png');
      const link = document.createElement('a');
      link.href = image;
      link.download = `${new Date().toISOString()}-wallpaper.png`;
      link.click();

      console.log('Wallpaper downloaded successfully');
    } catch (error) {
      console.error('Error downloading wallpaper:', error);
    }
  };

  return (
    <div className="mx-auto grid h-[calc(100%_-_70px)] w-full max-w-3xl place-items-center bg-red-50">
      <button onClick={handleDownload}>Download</button>
      <div> 
      <div
        ref={wallpaperRef}
        id="wallpaper"
        className="grid aspect-[9/21] w-full place-items-center"
        style={{
          background: 'blue',
          padding: '100px',
          transformOrigin: 'top center',
        }}
      >
        <p
          style={{
            fontSize: '44px',
              fontFamily: 'Instrument Serif',
            fontWeight: '900',
          }}
        >
          Some amazing text here
        </p>
      </div>
      </div>
    </div>
  );
};

export default DownloadWallpaperPage;
