import type { Metadata } from 'next';
import { Instrument_Serif, Crimson_Pro, Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/footer';

const instrumentSerif = Instrument_Serif({
  variable: '--font-instrument-serif',
  subsets: ['latin'],
  weight: '400',
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const crimsonPro = Crimson_Pro({
  variable: '--font-crimson-pro',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${instrumentSerif.variable} ${crimsonPro.variable} ${inter.variable} font-inter antialiased`}>
        <main className="relative flex flex-col min-h-dvh md:min-h-screen min-w-0">
          {/* <Navbar /> */}
          <div className="grow-1">
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
